#!/bin/bash


if [[ "$(uname -a | grep -i kali)" ]]; then
	sudo rm -rf /usr/local/bin/shell
	cd ~/; sudo ln -s ~/Shell/shell.py /usr/local/bin/shell
	echo "RELINKED"

else
	echo "Operating System Unsupported"
        fi

